name: "Pull Request Checks"

on:
  pull_request:

jobs:
  ##
  # install
  ##

  install:
    name: "Install"
    runs-on: ubuntu-latest
    steps:
      - name: "🛎 Checkout"
        uses: actions/checkout@v4
      - name: "📦 Setup pnpm Dependencies"
        uses: ./.github/actions/use-pnpm-dependencies

  ##
  # validation
  ##

  validate_pr_title:
    name: "Validate PR Title"
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: "🛎 Checkout"
        uses: actions/checkout@v4
      - name: "📦 Setup pnpm Dependencies"
        uses: ./.github/actions/use-pnpm-dependencies
      - name: "✅ Validate"
        run: echo ${{ github.event.pull_request.title }} | pnpm exec commitlint

  ##
  # lint, build documentation, build package and test
  ##

  lint:
    name: "Lint"
    needs: [install, validate_pr_title]
    runs-on: ubuntu-latest
    steps:
      - name: "🛎 Checkout"
        uses: actions/checkout@v4
      - name: "📦 Setup pnpm Dependencies"
        uses: ./.github/actions/use-pnpm-dependencies
      - name: "👕 Lint"
        run: pnpm lint

  type_check:
    name: "Type Check"
    needs: [install, validate_pr_title]
    runs-on: ubuntu-latest
    steps:
      - name: "🛎 Checkout"
        uses: actions/checkout@v4
      - name: "📦 Setup pnpm Dependencies"
        uses: ./.github/actions/use-pnpm-dependencies
      - name: "🔍 Type Check"
        run: pnpm check:types

  build_documentation:
    name: "Build Documentation"
    needs: [install, validate_pr_title]
    runs-on: ubuntu-latest
    steps:
      - name: "🛎 Checkout"
        uses: actions/checkout@v4
      - name: "📦 Setup pnpm Dependencies"
        uses: ./.github/actions/use-pnpm-dependencies
      - name: "🏗️ Build"
        run: pnpm build:docs

  build_package:
    name: "Build Package"
    needs: [install, validate_pr_title]
    runs-on: ubuntu-latest
    steps:
      - name: "🛎 Checkout"
        uses: actions/checkout@v4
      - name: "📦 Setup pnpm Dependencies"
        uses: ./.github/actions/use-pnpm-dependencies
      - name: "🏗️ Build"
        run: pnpm build

  test:
    name: "Test"
    needs: [install, validate_pr_title]
    runs-on: ubuntu-latest
    steps:
      - name: "🛎 Checkout"
        uses: actions/checkout@v4
      - name: "📦 Setup pnpm Dependencies"
        uses: ./.github/actions/use-pnpm-dependencies
      - name: "🧪 Test"
        run: pnpm test
