name: "Pull Request Checks"

on:
  pull_request:

jobs:
  ##
  # install
  ##

  install:
    name: "Install"
    runs-on: ubuntu-latest
    steps:
      - name: "🛎 Checkout"
        uses: actions/checkout@v4
      - name: "📦 Setup pnpm Dependencies"
        uses: ./.github/actions/use-pnpm-dependencies

  ##
  # validation
  ##

  validate_pr_title:
    name: "Validate PR Title"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: "🛎 Checkout"
        uses: actions/checkout@v4
      - name: "📦 Setup pnpm Dependencies"
        uses: ./.github/actions/use-pnpm-dependencies
      - name: "📥 Get PR Title"
        id: get_pr_title
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const { data } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });
            return data.title;
      - name: "✅ Validate"
        run: echo "${{ steps.get_pr_title.outputs.result }}" | pnpm exec commitlint

  ##
  # lint, check types and test
  ##

  lint:
    name: "Lint"
    needs: [install, validate_pr_title]
    runs-on: ubuntu-latest
    steps:
      - name: "🛎 Checkout"
        uses: actions/checkout@v4
      - name: "📦 Setup pnpm Dependencies"
        uses: ./.github/actions/use-pnpm-dependencies
      - name: "👕 Lint"
        run: pnpm lint

  type_check:
    name: "Type Check"
    needs: [install, validate_pr_title]
    runs-on: ubuntu-latest
    steps:
      - name: "🛎 Checkout"
        uses: actions/checkout@v4
      - name: "📦 Setup pnpm Dependencies"
        uses: ./.github/actions/use-pnpm-dependencies
      - name: "🔍 Type Check"
        run: pnpm check:types

  test:
    name: "Test"
    needs: [install, validate_pr_title]
    runs-on: ubuntu-latest
    steps:
      - name: "🛎 Checkout"
        uses: actions/checkout@v4
      - name: "📦 Setup pnpm Dependencies"
        uses: ./.github/actions/use-pnpm-dependencies
      - name: "🧪 Test"
        run: pnpm test
